Support DCTDecodeFilter, which is no-op, actually
rsc/pdf pull request #15
Opened 2017-07-09 10:14 UTC by fawick

2017-08-01 16:00 UTC, mpl commented
I'd suggest adding a tiny PDF in a testdata dir, with such an embedded image, plus a decoding test, but I see the lib does not have any tests at all, so maybe that's not wanted...

2017-08-01 16:43 UTC, mpl requested changes

2017-08-01 16:43 UTC, mpl commented on read.go
> +	case "DCTDecode":
// DCTDecode indicates that the Image XObject data is a full JPEG encoded image, so we return the original reader as is, and leave it up to the caller to decode the image.

2017-08-01 16:45 UTC, mpl commented
well, @bradfitz suggested a test too, so maybe that change can also be the one that introduces the first test.

2017-08-01 16:48 UTC, mpl commented
@josharian can we humbly ping you to have a look at this PR please?

2017-08-01 17:01 UTC, josharian commented
Tests are definitely welcome. I looked at the change, and it seems fine to me, but I really know ~0 about PDFs, and I'm not at a point now where I want to learn enough to take ownership of this repo. Sorry.

2017-08-02 05:18 UTC, fawick commented on read.go
> +	case "DCTDecode":
Good idea. thanks. Done.

2017-08-02 05:26 UTC, fawick commented
Okay, I will supply a test tonight.

@bradfitz, @mpl Given all the open PRs, is it worth considering to fork and maintain this package under go4.org?

2017-08-11 16:27 UTC, mpl commented on read_test.go
> +		testscan = "testdata/testscan.pdf"
50K seems a bit large for such a basic test imho. It does not have to be a real scan coming from your scanner, as long as it is structured the same. Is it difficult to forge a pdf with a an  image of less than 1K in it?
Examples of tiny images: camlistore.org/pkg/images/testdata

2017-08-11 16:29 UTC, mpl commented on read_test.go
> +}
we should probably check that the decoded image is what we expect. we'd usually check it pixel by pixel but that might be overkill here, so it's probably ok to e.g. check the hashsum of its bytes against a hardcoded hashsum of what we know to be the initial image.

2017-08-11 16:40 UTC, mpl commented
@fawick to answer your question about forking: given that nobody seems to be willing to own that repo, then yes, it probably will come to this. I doubt it'll be on go4.org though. As far as Camlistore is concerned, simply vendoring github.com/fawick/pdf (which is in effect similar to what you were proposing initially) is probably the way to go.

Let's finish the review on here first though.

2026-08-17 10:45 UTC, closed without merging